[feat] add debugging info (#45)
[feat] add signing signature

diff --git a/.github/workflows/ci-s3.yml b/.github/workflows/ci-s3.yml
--- a/.github/workflows/ci-s3.yml
+++ b/.github/workflows/ci-s3.yml
@@ -5,14 +5,13 @@ on:
   push:
     branches:
       - main
-  # # TESTING ONLY
   # pull_request:
   #   branches:
   #     - main
 
 permissions:
   id-token: write
-  contents: write
+  contents: read
   pull-requests: write
   actions: write
 
@@ -23,7 +22,7 @@ env:
   BIN_NAME: story
 
 jobs:
-  # Add  timestamp
+  # Add timestamp
   Timestamp:
     uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main
 
@@ -37,7 +36,23 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
+        uses: actions/checkout@v4.1.5  # Simplified reference
+        with:
+          fetch-depth: 0  # Ensure full history is fetched
+
+      - name: Configure Git to use Personal Access Token
+        run: |
+          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
+
+      - name: Configure GOPRIVATE
+        run: |
+          go env -w GOPRIVATE="github.com/piplabs/*"
+
+      - name: Clear Go module cache
+        run: go clean -modcache
+
+      - name: Run go mod tidy
+        run: go mod tidy
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -72,7 +87,10 @@ jobs:
 
           echo "Building for $GOOS/$GOARCH..."
           cd client
-          env GOOS=$GOOS GOARCH=$GOARCH go build -o $BIN_NAME > /dev/null 2>&1
+          env GOOS=$GOOS GOARCH=$GOARCH go build -o $BIN_NAME -v || {
+            echo "Build failed. Exiting..."
+            exit 1
+          }
 
           # Apply chmod only for non-windows platforms
           if [ "$GOOS" != "windows" ]; then
